name: hushify-infrastructure
services:
  - name: db
    image: postgres:15-alpine
    bindings:
      - port: 5432
    env:
      - name: POSTGRES_DB
        value: example.db
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
  - name: rabbit
    image: rabbitmq:3-management-alpine
    bindings:
      - name: rabbitmq
        port: 5672
        protocol: rabbitmq
      - name: management
        port: 15672
        containerPort: 15672
        protocol: http
  - name: mailhog
    image: mailhog/mailhog
    bindings:
      - name: smtp
        port: 1025
        containerPort: 1025
        protocol: smtp
      - name: ui
        port: 8025
        containerPort: 8025
        protocol: http